package com.tingeso.m5service.enums;

public enum ReservationState {
    PENDING, // PAYMENT PENDING
    CONFIRMED, // PAYMENT COMPLETED
    CANCELED, // RESERVATION CANCELED
    COMPLETED, // RESERVATION COMPLETED (TOUR COMPLETED)
    IN_PROGRESS, // RESERVATION IN PROGRESS (TOUR IN PROGRESS)
}
