server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_ZONE}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI}
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: tour-packages-service
              uri: lb://m2-service
              predicates:
                - Path=/api/tour-packages/**

            - id: tour-packages-search-service
              uri: lb://m3-service
              predicates:
                - Path=/api/search/tour-packages/**

            - id: reservations-service
              uri: lb://m4-service
              predicates:
                - Path=/api/reservations/**

            - id: discounts-service
              uri: lb://m4-service
              predicates:
                - Path=/api/discounts/**

            - id: transactions-service
              uri: lb://m5-service
              predicates:
                - Path=/api/transactions/**

            - id: reservations-follow-service
              uri: lb://m6-service
              predicates:
                - Path=/api/follow/reservations/**

            - id: reports-service
              uri: lb://m7-service
              predicates:
                - Path=/api/reports/**