server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_ZONE}:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${KEYCLOAK_HOST}:7080/realms/tingeso-2-realm/protocol/openid-connect/certs
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: tour-packages-service
              uri: lb://m2-service
              predicates:
                - Path=/api/tour-packages/**

            - id: tour-packages-search-service
              uri: lb://m3-service
              predicates:
                - Path=/api/search/tour-packages/**

            - id: reservations-service
              uri: lb://m4-service
              predicates:
                - Path=/api/reservations/**

            - id: discounts-service
              uri: lb://m4-service
              predicates:
                - Path=/api/discounts/**