apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  root_password: root_password
  username: user_tingeso
  user_password: pass_tingeso
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
type: Opaque
stringData:
  admin_password: admin