# CONFIG-SERVER
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-deployment
  labels:
    role: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: benjaminoq/ev-2-tingeso-config-server:latest
          ports:
            - containerPort: 8081
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: config-service
spec:
  type: ClusterIP
  selector:
    app: config-server
  ports:
    - port: 8081
      targetPort: 8081

---
# EUREKA-SERVER
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server-deployment
  labels:
    role: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: benjaminoq/ev-2-tingeso-eureka-server:latest
          ports:
            - containerPort: 8761
              protocol: TCP
          env:
            - name: CONFIG_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: CONFIG_HOST
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
spec:
  type: ClusterIP
  selector:
    app: eureka-server
  ports:
    - port: 8761
      targetPort: 8761