server:
  port: 8081

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/lBenjaminOrtegal/Evaluacion-2-Tingeso
          search-paths: config-data